version: '3'
services:
  sdk:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: .
      dockerfile: Dockerfile
    image: cobrefacil-sdk
    container_name: cobrefacil-sdk
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
